export const VALIDATOR_SERVICE = 'VALIDATOR_SERVICE';
export const VALIDATOR_PATTERN_NEW = 'VALIDATOR_PATTERN_NEW';
export const VALIDATOR_PATTERN_DELETED = 'VALIDATOR_PATTERN_DELETED';

export enum eVALIDATOR_ACTION {
  NEW = 'new',
  DELETE = 'delete',
}
