export const DATAFIELD_SERVICE = 'DATAFIELD_SERVICE';
export const DATAFIELD_PATTERN_NEW = 'DATAFIELD_PATTERN_NEW';
export const DATAFIELD_PATTERN_CHANGE_NAME = 'DATAFIELD_PATTERN_CHANGE_NAME';
export const DATAFIELD_PATTERN_LOCKED = 'DATAFIELD_PATTERN_LOCKED';
export const DATAFIELD_PATTERN_UNLOCKED = 'DATAFIELD_PATTERN_UNLOCKED';
export const DATAFIELD_PATTERN_DELETED = 'DATAFIELD_PATTERN_DELETED';
export const DATAFIELD_VALIDATOR_PATTERN_ADD =
  'DATAFIELD_VALIDATOR_PATTERN_ADD';
export const DATAFIELD_VALIDATOR_PATTERN_REMOVEED =
  'DATAFIELD_VALIDATOR_PATTERN_REMOVED';

export enum eDATAFIELD_ACTION {
  NEW = 'new',
  LOCK = 'lock',
  CHANGE_FIELDNAME = 'change_fieldname',
  UNLOCK = 'unlock',
  DELETE = 'delete',
  ADD_VALIDATOR = 'ADD_VALIDATOR',
  REMOVE_VALIDATOR = 'REMOVE_VALIDATOR',
}
