export const CLIENT_SERVICE = 'CLIENT_SERVICE';
export const CLIENT_PATTERN_NEW = 'CLIENT_PATTERN_NEW';
export const CLIENT_PATTERN_ADD_TARGET = 'CLIENT_PATTERN_ADD_TARGET';
export const CLIENT_PATTERN_DELETE_TARGET = 'CLIENT_PATTERN_DELETE_TARGET';
export const CLIENT_PATTERN_ADD_DATAPASS = 'CLIENT_PATTERN_ADD_DATAPASS';
export const CLIENT_PATTERN_DELETE_DATAPASS = 'CLIENT_PATTERN_DELETE_DATAPASS';
export const CLIENT_PATTERN_ADD_DATAPASS_TO_TARGET =
  'CLIENT_PATTERN_ADD_DATAPASS_TO_TARGET';
export const CLIENT_PATTERN_REMOVE_DATAPASS_TO_TARGET =
  'CLIENT_PATTERN_REMOVE_DATAPASS_TO_TARGET';

export const CLIENT_PATTERN_DELETED = 'CLIENT_PATTERN_DELETED';

export enum eCLIENT_ACTION {
  NEW = 'NEW',
  DELETE = 'DELETE',
  TARGET_ADD = 'TARGET_ADD',
  TARGET_DELETE = 'TARGET_DELETE',
  DATAPASS_ADD = 'DATAPASS_ADD',
  DATAPASS_DELETE = 'DATAPASS_DELETE',
  TARGET_DATAPASS_ADDED = 'TARGET_DATAPASS_ADDED',
  TARGET_DATAPASS_REMOVED = 'TARGET_DATAPASS_REMOVED',
}
